### ISSUE TITLE
Make "app" a mandatory option when creating a new app

### ISSUE THREAD

**Issue by lennym** [UKHomeOfficeForms/hof-generator#5]
A default of "default-app" isn't actually useful, because it will need to be changed in roughly 100% of implementations, and it's a lot more work to change after the fact than provide the option at generate time.

Instead make the user provide an app name as an option.

**Comment by JoeChapman** [comment]
Yep, make it mandatory

**Comment by lennym** [comment]
I think this is resolved now by using the directory name as default instead.
